import "./globals.css";
import { Noto_Sans_Thai } from "next/font/google";
import Navbar from "./layouts/Navbar";
import Footer from "./layouts/Footer";

const notosansthai = Noto_Sans_Thai({ subsets: ["latin"] });

export const metadata = {
  title: "Neang.Dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notosansthai.className}>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
